/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("Entropy.kotlin-common-conventions")
    application
}

dependencies {
    implementation("com.miglayout:miglayout-swing:5.2")
    implementation("javax.mail:javax.mail-api:1.6.2")
    implementation(project(":core"))
}

application {
    // Define the main class for the application.
    mainClass.set("EntropyMain")
}
