
package screen;

import java.awt.BorderLayout;
import java.awt.Color;

import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

public class ChangeLog extends JFrame 
{
	public ChangeLog() 
	{
		setTitle("Change Log");
		setSize(500, 570);
		getContentPane().setLayout(new BorderLayout(0, 0));
		getContentPane().add(scrollPane);
		textArea.setForeground(Color.BLACK);
		textArea.setBackground(Color.WHITE);
		textArea.setEditable(false);
		appendChangeLog();
		scrollPane.setViewportView(textArea);
	}
	
	private final JScrollPane scrollPane = new JScrollPane();
	private final JTextArea textArea = new JTextArea();
	
	private void appendChangeLog()
	{
		textArea.setText("");
		
		textArea.append("\n--------- Version 7.0.0 ---------");
		textArea.append("\n");
		textArea.append("\n+ Achievements (now 80 total)");
		textArea.append("\n= Fixed bugs with perfect bid achievements");
		textArea.append("\n= Certain achievements now not unlockable if playing with card reveal");
		textArea.append("\n= Fixed a bug where games got stuck when a player left");
		textArea.append("\n= Fixed various problems when observing a game where a player had left");
		textArea.append("\n= Stopped the replay conversion triggering for a clean install of the game");
		textArea.append("\n= Optimised XML construction and parsing");
		textArea.append("\n");
		textArea.append("\n--------- Version 6.2.2 ---------");
		textArea.append("\n");
		textArea.append("\n= Made the online rooms table sort by player count when the lobby is first opened");
		textArea.append("\n= Online rooms table will remain correctly sorted when rooms are added or updated");
		textArea.append("\n= Fixed a bug where the revealed card was displayed twice in the Bid History for Vectropy");
		textArea.append("\n= Fixed a bug where notifications stopped working if none were sent for a period of time");
		textArea.append("\n= Fixed a bug deobfuscating stack lines containing <init>");
		textArea.append("\n");
		textArea.append("\n--------- Version 6.2.1 ---------");
		textArea.append("\n");
		textArea.append("\n+ Created an index file to improve performance of Replay Viewer for a large number of files");
		textArea.append("\n= Made automatic updates work for Apple operating systems");
		textArea.append("\n= Fixed a bug saving replays caused by special characters in the player name");
		textArea.append("\n= Fixed a bug where AI challenges would show as having revealed a card");
		textArea.append("\n");
		textArea.append("\n--------- Version 6.2.0 ---------");
		textArea.append("\n");
		textArea.append("\n+ Created separate notification queues so unrelated notifications can be sent concurrently");
		textArea.append("\n= Statistics updates are now sent as notifications rather than being requested");
		textArea.append("\n= Fixed a bug where jacks were incorrectly positive for the first round online");
		textArea.append("\n= Made server notifications more robust (wait/notify)");
		textArea.append("\n= Improved 'tidy up' of the screen after an online game finishes");
		textArea.append("\n= Fixed a bug with standing up immediately after a game");
		textArea.append("\n= Client logs are now sent via the server rather than directly from the client");
		textArea.append("\n= Improved client obfuscation");
		textArea.append("\n= Client logs are automatically deobfuscated before being emailed");
		textArea.append("\n");
		textArea.append("\n--------- Version 6.1.1 ---------");
		textArea.append("\n");
		textArea.append("\n+ Validation of replay contents when trying to open them from the replay viewer");
		textArea.append("\n= Refactored/improved the replay viewer code to be more object oriented");
		textArea.append("\n= Fixed deadlock caused by new synchronization when logging in with a reset password");
		textArea.append("\n- Slow/intensive validation of all files when opening replay viewer");
		textArea.append("\n");
		textArea.append("\n--------- Version 6.1.0 ---------");
		textArea.append("\n");
		textArea.append("\n+ HTML characters are now escaped wherever custom text can be displayed");
		textArea.append("\n= Removed polling from client/server communication");
		textArea.append("\n= Fixed a bug where observing didn't work if you joined a room before it was full");
		textArea.append("\n= Fixed bugs with disconnecting");
		textArea.append("\n= Client is now 'dual-threaded' to the server");
		textArea.append("\n");
		textArea.append("\n--------- Version 6.0.0 ---------");
		textArea.append("\n");
		textArea.append("\n+ Card reveal reward for 10 achievements. Jokers are now unlocked from the start");
		textArea.append("\n+ Entropy icon. ICO file is included in the install ZIP for use with shortcuts");
		textArea.append("\n+ Improved random suit icons, which are now used for online rooms");
		textArea.append("\n+ Updated API code/documentation to include card reveal");
		textArea.append("\n+ New bid display using suit icons");
		textArea.append("\n+ Reworked the layout of the gameplay preferences tab");
		textArea.append("\n+ A message will display in the chat when a player unlocks an achievement online");
		textArea.append("\n+ Made it possible to unlock Second Thoughts online");
		textArea.append("\n= Handicaps are now unlocked from the start");
		textArea.append("\n= Introduced better process for replay conversions");
		textArea.append("\n= Fixed a bug refreshing the replay viewer");
		textArea.append("\n= Fixed a bug with the scroll bar on the appearance preferences tab");
		textArea.append("\n= Fixed a bug selecting locked card backs (introduced in 5.3.0)");
		textArea.append("\n= Fixed a bug creating room copies online");
		textArea.append("\n= Fixed a synchronization bug with the lobby message");
		textArea.append("\n");
		textArea.append("\n--------- Version 5.4.1 ---------");
		textArea.append("\n");
		textArea.append("\n+ Made it possible to connect with multiple devices on the same IP");
		textArea.append("\n");
		textArea.append("\n--------- Version 5.4.0 ---------");
		textArea.append("\n");
		textArea.append("\n+ Automatic check for updates on startup - can be disabled via a misc preference");
		textArea.append("\n+ Batch file and EntropyUpdater files to allow smooth download and launch");
		textArea.append("\n");
		textArea.append("\n--------- Version 5.3.2 ---------");
		textArea.append("\n");
		textArea.append("\n= Background changes to client/server communication ready for Android");
		textArea.append("\n");
		textArea.append("\n--------- Version 5.3.1 ---------");
		textArea.append("\n");
		textArea.append("\n+ Option to change the value of Jacks to be -1");
		textArea.append("\n+ Online rooms with -1 Jack option, and a flag to represent this");
		textArea.append("\n+ Updated API code/documentation to include negative jacks");
		textArea.append("\n= Bug fix initialising the bid panel when continuing a Vectropy game");
		textArea.append("\n= Bug fix for intermittent problem refreshing the Leaderboard");
		textArea.append("\n= Removed internal concept of a 'Room ID', as room names are unique");
		textArea.append("\n");
		textArea.append("\n--------- Version 5.3.0 ---------");
		textArea.append("\n");
		textArea.append("\n+ Strategy API");
		textArea.append("\n+ Info tab for online games");
		textArea.append("\n= Fixed a bug with the location of online rooms on the screen");
		textArea.append("\n= Mass removal of old/duplicated/shitty code");
		textArea.append("\n");
		textArea.append("\n--------- Version 5.2.2 ---------");
		textArea.append("\n");
		textArea.append("\n= Improved email validation for online accounts");
		textArea.append("\n= Improved emailing of logs");
		textArea.append("\n= Reduced some font sizes to look better in Nimbus theme");
		textArea.append("\n= Bug fix for apple operating systems");
		textArea.append("\n= Leaving an online game during the first round will no longer count as a loss");
		textArea.append("\n");
		textArea.append("\n--------- Version 5.2.1 ---------");
		textArea.append("\n");
		textArea.append("\n= Changed package structure");
		textArea.append("\n= Bug fixes");
		textArea.append("\n= Leaderboard now only shows non-zero achievement counts");
		textArea.append("\n");
		textArea.append("\n--------- Version 5.2.0 ---------");
		textArea.append("\n");
		textArea.append("\n+ Ability to change the overall Look & Feel in Appearance preferences");
		textArea.append("\n+ Online release");
		textArea.append("\n");
		textArea.append("\n--------- Version 5.1.0 ---------");
		textArea.append("\n");
		textArea.append("\n+ Global stats for the Leaderboard");
		textArea.append("\n+ Link between online account and email for password recovery");
		textArea.append("\n+ Account settings online to allow changing of password and/or email");
		textArea.append("\n+ Bug Report feature");
		textArea.append("\n+ Hidden achievements");
		textArea.append("\n+ EV Strategy for Vectropy");
		textArea.append("\n+ Room name to saved replays");
		textArea.append("\n= Client/Server traffic is now encrypted");
		textArea.append("\n= Replays can be deleted in bulk");
		textArea.append("\n");
		textArea.append("\n--------- Version 5.0.0 ---------");
		textArea.append("\n");
		textArea.append("\n+ EntropyOnline");
		textArea.append("\n+ Rewards for 40, 45 and 50 achievements");
		textArea.append("\n+ New card backs to unlock for every 5 achievements earned");
		textArea.append("\n+ Achievements (Citizen's Arrest, Connected, Railbird, Social, Spaceman, Werewolf)");
		textArea.append("\n+ Progress Bar for Simulation Dialog");
		textArea.append("\n= Fixed performance issues with the Replay Viewer");
		textArea.append("\n= Made message dialogs more consistent");
		textArea.append("\n= Improved the way Entropy detects that it's already running");
		textArea.append("\n");
		textArea.append("\n--------- Version 4.1.2 ---------");
		textArea.append("\n");
		textArea.append("\n= Fixed a bug where losses were double-counted");
		textArea.append("\n= Help dialog now refreshes properly when Vectropy is unlocked");
		textArea.append("\n= Fixed a bug where the bid slider always showed clubs on continuing a game");
		textArea.append("\n= Fixed a bug where some continued games started with the wrong player");
		textArea.append("\n= Fixed a bug where the replay viewer sometimes refreshed with the wrong filters");
		textArea.append("\n= Removed a broken hyperlink from the help dialog");
		textArea.append("\n= Made some improvements to the screen layout");
		textArea.append("\n= Made it possible to have a file replay and an in-game replay open at once");
		textArea.append("\n= The in-game replay now automatically closes between games");
		textArea.append("\n");
		textArea.append("\n--------- Version 4.1.1 ---------");
		textArea.append("\n");
		textArea.append("\n= Fixed a bug with opening the help for the first time");
		textArea.append("\n= Fixed 'Distracted' achievement so it isn't earned when a game is over");
		textArea.append("\n= Fixed a bug with opening file replays on the last round");
		textArea.append("\n= Changed the order of achievement/reward popups");
		textArea.append("\n");
		textArea.append("\n--------- Version 4.1.0 ---------");
		textArea.append("\n");
		textArea.append("\n+ Test tube representation of achievement progress");
		textArea.append("\n+ Username for debugging");
		textArea.append("\n+ Unlockable rewards");
		textArea.append("\n+ Achievements (Easy as 1,2,3, Distracted)");
		textArea.append("\n= Imported and exported replays are now forced to have the '.ent' extension");
		textArea.append("\n= Replay files are now encoded");
		textArea.append("\n= The in-game replay will now update while open as a game progresses");
		textArea.append("\n= Fixed a bug with changing appearance preferences");
		textArea.append("\n= Fixed a couple of bugs with starting a new game immediately after losing a challenge");
		textArea.append("\n");
		textArea.append("\n--------- Version 4.0.0 ---------");
		textArea.append("\n");
		textArea.append("\n+ Vectropy Mode");
		textArea.append("\n+ Vectropy achievements (The Mathematician, Base Ten, Five Squared, Half-Century)");
		textArea.append("\n+ Vectropy mode to Simulator");
		textArea.append("\n+ 'Configure Columns' option to replay viewer");
		textArea.append("\n+ Columns to replay viewer: game mode and number of rounds");
		textArea.append("\n+ Two new decks and the ability to play with four colours");
		textArea.append("\n+ New jokers and card backs");
		textArea.append("\n+ New help pages for Vectropy");
		textArea.append("\n= Redesigned replay viewer and made it resizable");
		textArea.append("\n= Separate statistics for games played/won in Vectropy");
		textArea.append("\n= Replay viewer now caches values so refreshing is faster");
		textArea.append("\n= Fixed the simulator which got broken in 3.2.1");
		textArea.append("\n= Fixed a bug with the maximum bid when jokers are in play");
		textArea.append("\n= Changes to game speed now take effect immediately");
		textArea.append("\n");
		textArea.append("\n--------- Version 3.2.1 ---------");
		textArea.append("\n");
		textArea.append("\n= Refactored code to make adding other variants easier");
		textArea.append("\n");
		textArea.append("\n--------- Version 3.2.0 ---------");
		textArea.append("\n");
		textArea.append("\n+ Achievements (The Chimera, Precision, Underdog I-III)");
		textArea.append("\n+ EV Strategy");
		textArea.append("\n+ Hyperlinking to the help dialog");
		textArea.append("\n+ Glossary and Clearing Data help pages");
		textArea.append("\n+ Command Bar");
		textArea.append("\n+ Flags for handicaps to replace \"x/y\" notation");
		textArea.append("\n+ Emailing of logs (both automatic and manual)"); 
		textArea.append("\n+ Date and Flag filter options to Replay Viewer");
		textArea.append("\n= Tightened error handling across all classes");
		textArea.append("\n= Replay Viewer now shows multiple flags");
		textArea.append("\n= Fixed bug where you could change the strategy of opponents mid-game");
		textArea.append("\n= Search terms are now highlighted in the help dialog");
		textArea.append("\n= Fixed a bug with refreshing the main screen");
		textArea.append("\n");
		textArea.append("\n--------- Version 3.1.0 ---------");
		textArea.append("\n");
		textArea.append("\n+ Help dialog");
		textArea.append("\n+ Five new achievements");
		textArea.append("\n+ Icons for replay viewer, replays, help and achievements");
		textArea.append("\n= Time played in statistics now updates in real-time");
		textArea.append("\n= Disabled multiple instances");
		textArea.append("\n= Fixed perfect game achievements to work with handicaps");
		textArea.append("\n= Sorting by date now works properly on the replay tables");
		textArea.append("\n= Replays can now be viewed using the return key with a row selected");
		textArea.append("\n- Simulation achievements");
		textArea.append("\n");
		textArea.append("\n--------- Version 3.0.0 ---------");
		textArea.append("\n");
		textArea.append("\n+ Option to save replays as files, and new 'Miscellaneous' section in Preferences.");
		textArea.append("\n+ Replay Viewer to play back saved replays");
		textArea.append("\n+ Filter options to replay viewer");
		textArea.append("\n+ Ability to export and import replays, and a separate table for imported replays");
		textArea.append("\n+ Ability to sort replays");
		textArea.append("\n+ Random game icon");
		textArea.append("\n+ Options to play blind and/or start a game with less cards than opponents");
		textArea.append("\n+ Card counter next to the bidding area");
		textArea.append("\n= Fixed bug where Mark strategy would occasionally jump bid");
		textArea.append("\n= Now don't allow starting a new game during opponent's turn");
		textArea.append("\n= Preferences and Simulation dialogs are now modal");
		textArea.append("\n= Now only allow one instance of non-modal dialogs");
		textArea.append("\n= Changed clear data option to be more flexible and to display useful messages");
		textArea.append("\n= Achievements dialog now refreshes in real-time");
		textArea.append("\n= Appearance and misc. preferences now take effect immediately");
		textArea.append("\n");
		textArea.append("\n--------- Version 2.4.0 ---------");
		textArea.append("\n");
		textArea.append("\n+ Replay screen - can now look back at prior hands throughout a game");
		textArea.append("\n");
		textArea.append("\n--------- Version 2.3.2 ---------");
		textArea.append("\n");
		textArea.append("\n+ Asterisk to denote who started a round");
		textArea.append("\n+ Validation to preferences dialog so names can only be 1-10 characters long");
		textArea.append("\n+ Now allow Mark Strategy for 3 or more players");
		textArea.append("\n= Fixed bug where changing preferences mid-game would affect strategies");
		textArea.append("\n= Fixed bug where 'bid history' font would occasionally glitch");
		textArea.append("\n");
		textArea.append("\n--------- Version 2.3.1 ---------");
		textArea.append("\n");
		textArea.append("\n+ Delay on opponent's actions with slow/medium/fast speed settings");
		textArea.append("\n+ Win rate to statistics");
		textArea.append("\n+ Change Log to \"About...\" option");
		textArea.append("\n= Fixed time played in statistics to display as HH:MM:SS");
		textArea.append("\n= Fixed bug where starting a new game after the first challenge counted as a loss, but gave no warning");
		textArea.append("\n= Now only record a game as played once it's over");
		textArea.append("\n");
		textArea.append("\n--------- Version 2.3.0 ---------");
		textArea.append("\n");
		textArea.append("\n+ Achievements (now 30 total)");
		textArea.append("\n+ Second achievement popup for multiple at same time");
		textArea.append("\n+ Continue Game ability with autosave option in preferences");
		textArea.append("\n+ Statistics dialog");
		textArea.append("\n= Renamed time achievements to be running related");
		textArea.append("\n= No longer require player to click 'Next' to register the end of a game");
		textArea.append("\n");
		textArea.append("\n--------- Version 2.2.0 ---------");
		textArea.append("\n");
		textArea.append("\n+ Achievements dialog (gardener, lion, burglar, caveman, five/fifteen minutes)");
		textArea.append("\n+ Preferences are now saved to a file so they remain set for next time the application is launched");
		textArea.append("\n= Fixed bug where clicking 'clubs' at start of a new round/game would raise minimum bid to 2");
		textArea.append("\n= Fixed bug where 'next' button and result of the round would stay on the screen if you started a new game");
		textArea.append("\n= Fixed simulator bug where the joker value was coming from preferences");
		textArea.append("\n");
		textArea.append("\n--------- Version 2.1.2 ---------");
		textArea.append("\n");
		textArea.append("\n+ Randomise play order (simulation option)");
		textArea.append("\n+ Gameplay tab in simulation dialog");
		textArea.append("\n+ Suits and colours to slider display");
		textArea.append("\n= Now uses singular for bids of one");
		textArea.append("\n= Tweaks to Mark strategy (v1.2)");
		textArea.append("\n= Fixed bug where player wasn't re-enabled when starting a new game");
		textArea.append("\n");
		textArea.append("\n--------- Version 2.1.1 ---------");
		textArea.append("\n");
		textArea.append("\n+ New statistics in Simulation dialog: Win %, Challenge %, Challenge Success %, Perfect %");
		textArea.append("\n+ Force start (simulation option)");
		textArea.append("\n= Simulation dialog now displays percentages rather than raw data");
		textArea.append("\n= Simulation dialog shows results in a neat table");
		textArea.append("\n");
		textArea.append("\n--------- Version 2.1.0 ---------");
		textArea.append("\n");
		textArea.append("\n+ Simulation Dialog");
		textArea.append("\n= Fixed bug where opponent one wasn't re-enabled when starting a new game");
		textArea.append("\n= Fixed bug where game would break if only the player and opponent three were left");
		textArea.append("\n");
		textArea.append("\n--------- Version 2.0.1 ---------");
		textArea.append("\n");
		textArea.append("\n+ Logging to help with another bug that was spotted");
		textArea.append("\n= Fixed bug where two & three player games weren't finishing correctly");
		textArea.append("\n= Fixed bug where second player to go out wasn't disabled properly");
		textArea.append("\n");
		textArea.append("\n--------- Version 2.0.0 ---------");
		textArea.append("\n");
		textArea.append("\n+ Game now allows up to four players");
		textArea.append("\n= Basic strategy amended to work for arbitrary number of players");
		textArea.append("\n= Slider maximum capped to account for increased cards in play");
		textArea.append("\n");
		textArea.append("\n--------- Version 1.1.1 ---------");
		textArea.append("\n");
		textArea.append("\n+ Names for players now appear above their cards");
		textArea.append("\n+ Loads of background code ready for four players");
		textArea.append("\n= Now can't change joker settings mid-game");
		textArea.append("\n= Tweaked Mark's strategy to work more effectively");
		textArea.append("\n= Fixed bug where opponent could sometimes bid illegally");
		textArea.append("\n");
		textArea.append("\n--------- Version 1.1.0 ---------");
		textArea.append("\n");
		textArea.append("\n+ Preferences window is now in two tabs - appearance and gameplay");
		textArea.append("\n+ Ability to name the opponent");
		textArea.append("\n+ Ability to select the opponent's strategy: Mark or Basic");
		textArea.append("\n+ Two random strategies - per move and per round");
		textArea.append("\n= Resized the window and changed the layout in preparation for four players");
		textArea.append("\n");
		textArea.append("\n--------- Version 1.0.3 ---------");
		textArea.append("\n");
		textArea.append("\n+ Added console to 'Help' menu");
		textArea.append("\n+ Added ctrl+l and ctrl+n shortcuts");
		textArea.append("\n+ Added option to set number of jokers and joker value (up to 4 for both)");
		textArea.append("\n+ Cards now grey out when there's a challenge if they're not of the relevant suit");
		textArea.append("\n= Fixed and tidied up the logging");
		textArea.append("\n= Fixed the slider max values to be correct with jokers in play");
		textArea.append("\n= Removed value labels from slider, replaced with a box to the right displaying the current selection");
		textArea.append("\n");
		textArea.append("\n--------- Version 1.0.2 ---------");
		textArea.append("\n");
		textArea.append("\n+ Logging to help with fixing bugs");
		textArea.append("\n= Fixed bug with bidding the wrong suit");
		textArea.append("\n= Refactored some code and tided up in general");
		textArea.append("\n= Changed slider to show all values for now (will add label later)");
		textArea.append("\n");
		textArea.append("\n--------- Version 1.0.1 ---------");
		textArea.append("\n");
		textArea.append("\n+ New slider and button method of bidding");
		textArea.append("\n- Old spinner and combo box method of bidding");
		textArea.append("\n");
		textArea.append("\n--------- Version 1.0.0 ---------");
		textArea.append("\n");
		textArea.append("\n+ Creation:");
		textArea.append("\n+ Two player game against a simple fixed strategy");
		textArea.append("\n+ Preferences dialog with options to change card design, starting number of cards and include jokers");
		textArea.append("\n");
		
		textArea.setCaretPosition(0);
		textArea.setLineWrap(true);
	}
}