/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("Entropy.kotlin-library-conventions")
}

dependencies {
    implementation("javax.mail:javax.mail-api:1.6.2")
    implementation("javax.activation:activation:1.1.1")
}